### ISSUE TITLE
Forecast Days Past 0 Not Working

### ISSUE THREAD

**Issue by rickskirch** [BME-nodeservers/docs#2]
ISY on Polisy V. 5.4.4
Polyglot 3.0.62
OpenWeatherMap 3.1.3
Open Weather Map Free API

I started with 2 forecast days and Forecast 0 was populated with data, but not Forecast  1.  Then I increased the Forecast variable to 3 and still, only 0 was populated.  Any advice.

- Rick

**Comment by bpaauwe** [comment]
Set the log level to debug, restart the node server and check the log.

**Comment by rickskirch** [comment]
Log without API keys attached

[log.txt](https://github.com/BME-nodeservers/docs/files/8840284/log.txt)

**Comment by bpaauwe** [comment]
It looks like it maybe encountering an error while trying to calculate the ETo value and aborting.

I just pushed out version 3.1.4  that adds error trapping around the calculation.  This should provide more details on what is failing and also allow it to continue processing forecast data so the other days populate.

You can install it by refreshing the store and then restarting the node server, it should automatically install the new version.

**Comment by rickskirch** [comment]
I refreshed the store and then restarted the node server.  It upgraded to 3.1.4, but nothing changed.  I then set debug level and restarted Polyglot and captured the log.
[log.txt](https://github.com/BME-nodeservers/docs/files/8841895/log.txt)
.

**Comment by rickskirch** [comment]
Any updates?

**Comment by bpaauwe** [comment]
Try entering the correct elevation.  Looking up your coordinates it says the elevation is 824 meters. It looks like you entered "2,664" which isn't a valid number.

**Comment by rickskirch** [comment]
Ok, that was it.  Not sure why forecast 0 worked, but I should have read it was in meters and not feet.  My bad. Thank you for the help.
