### ISSUE TITLE
Instructions for API Key

### ISSUE THREAD

**Issue by Adam-B0mb** [BME-nodeservers/docs#4]
Hello,
    It is not clear how how to properly generate the API Key.  I generated one on Ambientweather.net but it was missing the App Key.   I have the node configured but getting the error below.  I am thinking because I am missing the App Key.  Please point me to the steps..

ERROR    station:Query: Parsing failed: string indices must be integers

Thanks,
Adam

**Comment by bpaauwe** [comment]
Click the "create API key"  button on the AmbientWeather Website copy the resulting key and paste it into the "API Key" custom parameter.  That's it.

A parsing failure means the data returned by AmbientWeather can't be parsed by the node server.  It should report a different error it it was unable to connect to the server.

**Comment by Adam-B0mb** [comment]
Ah.. So how do I fix my problem?  Thanks for the quick response!

**Comment by Adam-B0mb** [comment]
> Click the "create API key" button on the AmbientWeather Website copy the resulting key and paste it into the "API Key" custom parameter. That's it.
> 
> A parsing failure means the data returned by AmbientWeather can't be parsed by the node server. It should report a different error it it was unable to connect to the server.

in case it helps others, I recreated the api key and it worked.
